const EMAIL__PATTERN = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/

const LARGE_SCREEN = 1279;
const MEDIUM_SCREEN = 954;
const SMALL_SCREEN = 767;

const SHORT_MOVIE_DURATION = 40;
export {EMAIL__PATTERN, LARGE_SCREEN, MEDIUM_SCREEN, SMALL_SCREEN, SHORT_MOVIE_DURATION}