const EMAIL__PATTERN = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/

const LARGE_SCREEN = 1279;
const MEDIUM_SCREEN = 954;
const SMALL_SCREEN = 767;

const LARGE_SCREEN_MOVIES = 16;
const MEDIUM_SCREEN_MOVIES = 12;
const SMALL_SCREEN_MOVIES = 6;
const MOBILE_SCREEN_MOVIES = 5

const LARGE_SCREEN_STEP = 4;
const MEDIUM_SCREEN_STEP = 3;
const SMALL_SCREEN_STEP = 2;

const SHORT_MOVIE_DURATION = 40;
export {EMAIL__PATTERN, LARGE_SCREEN, MEDIUM_SCREEN, SMALL_SCREEN, SHORT_MOVIE_DURATION ,LARGE_SCREEN_MOVIES, MEDIUM_SCREEN_MOVIES, SMALL_SCREEN_MOVIES, MOBILE_SCREEN_MOVIES, LARGE_SCREEN_STEP, MEDIUM_SCREEN_STEP, SMALL_SCREEN_STEP}